trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ramalho011/lorarchapi'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: Dockerfile
    tags: |
      $(imageName):latest
